// React/react/code/react_staging/src_06_github搜索PubSub版/components/search/Search.jsx
import React, {Component} from 'react'
import PubSub from 'pubsub-js'

export default class Search extends Component {

  search =()=>{
    //1.获取用户输入
    let keyWord = this.refs.keyWord.value.trim()
    //2.消息发布（）
    PubSub.publish('searchUser',keyWord)
    //3.清空用户输入
    this.refs.keyWord.value = ''
  }

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">Search Github Users</h3>
        <div>
          <input type="text" placeholder="enter the name you search" ref="keyWord"/>
          <button onClick={this.search}>Search</button>
        </div>
      </section>
    )
  }
}

// Vue/work/day10(vuex)/vuex-exec/src/components/search.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input type="text" placeholder="enter the name you search" v-model.lazy="serachName"/>
      <button @click="search">Search</button>
    </div>
  </section>
</template>

<script>
    import {mapActions} from "vuex";
    export default {
        name: "search",
        computed:{
          serachName:{
            get(){
              return this.$store.state.serachName
            },
            set(val){
              //修改仓库中的数据  转发一个action
              this.$store.dispatch("chaneSerachName",val)
            }
          }
        },
        methods:{
          ...mapActions(["search"])
        }
    }
</script>

<style scoped>

</style>
